apiVersion: v1
kind: Pod # Kind of the Kubernetes Resource
metadata:
  name: sa-frontend # Name of the Resource
spec: # defines the desired state for the resource
  containers:
    - image: rinormaloku/analysis-frontend # image used in app/01-pod-definition.yaml
      name: sa-frontend # Name for the container in the pod
      ports:
        - containerPort: 80 # Container listens to this port (indicator)
