apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: clusterscanner
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: hello-world
      server: https://kubernetes.default.svc
    - namespace: hello-world2
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
status: {}